### ISSUE TITLE
Initial config file written world-readable

### ISSUE THREAD

**Issue by jgbreezer** [Fitzsimmons/cmdipass#3]
As I (might) understand it, the initial config file generation needs to save a key in the ~/.cmdipass to identify the client and this authorises the client to request keepass credentials. Your code to generate this file (at least, in the linux release zip file I just downloaded) either uses default umask or sets one that allows it to be world-readable. I probably don't want that.

**Comment by Fitzsimmons** [comment]
Good catch!

I'll try to roll out a fix for this in the next couple of days.
